apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapp-deployment
  labels:
    app: shoppingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapp
  template:
    metadata:
      labels:
        app: shoppingapp
    spec:
      containers:
        - name: shoppingapp
          image: aksshoppingacrceos.azurecr.io/shoppingclient:v2
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: shoppingapi-configmap
                    key: shoppingapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
            - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapp-service
spec:
  type: LoadBalancer
  selector:
    app: shoppingapp
  ports:
    - protocol: TCP
      port: 80