apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapp-deployment
  labels:
    app: shoppingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapp
  template:
    metadata:
      labels:
        app: shoppingapp
    spec:
      containers:
        - name: shoppingapp
          image: voltsrage/shoppingapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: shoppingapi-configmap
                    key: shoppingapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapp-service
spec:
  type: NodePort
  selector:
    app: shoppingapp
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 31100